### ISSUE TITLE
Potential Babel 7 Problem

### ISSUE THREAD

**Issue by dmk255** [QuickBase/babel-plugin-styled-components-css-namespace#5]
Hello!

That you for writing this awesome plugin! It's exactly what my team is looking for.

On adding it to my babel config I've received the following error. My guess is this is due to me using babel 7 in conjunction with webpack 4. 

```
ERROR in ./src/index.js
Module build failed: TypeError: Cannot read property 'imports' of undefined
    at importLocalName (/Users/danielkezerashvili/code/forms/node_modules/@quickbaseoss/babel-plugin-styled-components-css-namespace/node_modules/babel-plugin-styled-components/lib/utils/detectors.js:15:45)
    at isCSSHelper (/Users/danielkezerashvili/code/forms/node_modules/@quickbaseoss/babel-plugin-styled-components-css-namespace/node_modules/babel-plugin-styled-components/lib/utils/detectors.js:41:46)
    at isHelper (/Users/danielkezerashvili/code/forms/node_modules/@quickbaseoss/babel-plugin-styled-components-css-namespace/node_modules/babel-plugin-styled-components/lib/utils/detectors.js:53:10)
    at exports.default (/Users/danielkezerashvili/code/forms/node_modules/@quickbaseoss/babel-plugin-styled-components-css-namespace/lib/visitors/cssNamespace.js:34:82)
    at PluginPass.TaggedTemplateExpression (/Users/danielkezerashvili/code/forms/node_modules/@quickbaseoss/babel-plugin-styled-components-css-namespace/lib/index.js:13:36)
    at newFn (/Users/danielkezerashvili/code/forms/node_modules/@babel/traverse/lib/visitors.js:223:21)
    at NodePath._call (/Users/danielkezerashvili/code/forms/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/Users/danielkezerashvili/code/forms/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/danielkezerashvili/code/forms/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/danielkezerashvili/code/forms/node_modules/@babel/traverse/lib/context.js:135:18)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./src
```

my babel config:
```JSON
"babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "shippedProposals": true,
          "targets": {
            "browsers": [
              "last 2 versions"
            ]
          }
        }
      ],
      "@babel/preset-react"
    ],
    "plugins": [
      "@quickbaseoss/babel-plugin-styled-components-css-namespace",
      "lodash",
      "transform-class-properties",
      [
        "styled-components",
        {
          "displayName": true
        }
      ]
    ]
  }
```

EDIT: The issue is shared with this issue https://github.com/styled-components/babel-plugin-styled-components/issues/96

**Comment by dmk255** [comment]
So it looks like the fix is to update `babel-plugin-styled-components`. I'll submit a PR to that effect
